### PR TITLE
Initial import/unpack IRO from shell support

### PR DESCRIPTION
**Pull request by unab0mb**

### CODE REVIEW

**Comment by TurBoss** [comment]
hello, 
doesn't the irosArc.exe do this by default?
```
irosArc.exe
Usage: IrosArc [Create|Extract|List|MakePatch|ApplyPatch] [ArchiveFile] (parameters)

IrosArc Create [ArchiveFile] [BaseFolder] [CompressionType]
    BaseFolder = folder to pack
    CompressionType = Nothing|Everything|ByExtension|ByContent

IrosArc Extract [ArchiveFile] [DestinationFolder] [filter]
    DestinationFolder = folder to extract into.
    Filter = (Optional) Filename(s) to extract.

IrosArc List [ArchiveFile]
    Describe contents of archive

IrosArc MakePatch [OriginalArchive] [NewArchive] [PatchFile] [CompressionType]
    OriginalArchive = original archive you want to make a patch for
    NewArchive = updated version you want the patch to update to
    PatchFile = location to save patch into

IrosArc ApplyPatch [ArchiveFile] [PatchFile]
    ArchiveFile = Original archive
    PatchFile = patch to apply
    Archive is updated IN PLACE. Take a backup copy first if you need to keep the original!
```

**Comment by unab0mb** [comment]
No. IrosArc is the tool, not the shell integration.

**Comment by TurBoss** [comment]
I'm sorry but what does shell integration means ?
:D thanks

**Comment by TurBoss** [comment]
thank you

**Pull request merged**
