### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by julianxhokaxhiu**
Remove unneeded files. Less clutter, more optimized build.

### CODE REVIEW

**Comment by TurBoss** [comment]
hey thanks for the clean up

is the mega.dll not required?

**Comment by julianxhokaxhiu** [comment]
Nope, I tested it on my side ( refreshed the list, downloaded an item and activated from the library, as well as run the game ). No errors as well as it is never reference by any of the projects 🤷‍♂

**Comment by TurBoss** [comment]
maybe because it falls back to gdrive but mega isn't working

https://github.com/TurBoss/7h/blob/master/IrosMega/MegaIros.cs#L118

**Review by TurBoss — CHANGES_REQUESTED** [review]
mega.dll is linked in code

**Comment by julianxhokaxhiu** [comment]
Removed mega.dll and LZMA.dll from the list, both are imported. The rest is not present anywhere in the project and can be safely deleted.

**Review by TurBoss — APPROVED** [review]

**Comment by TurBoss** [comment]
thanks

**Comment by julianxhokaxhiu** [comment]
thank you!

**Pull request merged**
